version: "3.2"

services:
  vscode:
    image: latexdevcontainer
    build:
        context: .
        args:
          HOST_UID: 1000
          HOST_GID: 1000
    volumes:
      - ../:/workspace
      # Docker socket to access Docker server
      - /var/run/docker.sock:/var/run/docker.sock
      # SSH directory
      - ~/.ssh:${HOME}/.ssh
      # For Windows without WSL, a copy will be made
      # from /tmp/.ssh to ~/.ssh to fix permissions
      # - ~/.ssh:/tmp/.ssh:ro
      # Shell history persistence
      - ~/.zsh_history:/root/.zsh_history:z
      # Git config
      - ~/.gitconfig:${HOME}/.gitconfig
      - ~/.zshrc:${HOME}/.zshrc
    environment:
      - TZ=
    entrypoint: ["zsh", "-c", "while sleep 1000; do :; done"]
 
