name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: First pdflatex run
        uses: dante-ev/latex-action@latest
        with:
          root_file: main.tex
          compiler: pdflatex

      - name: Second pdflatex run
        uses: dante-ev/latex-action@latest
        with:
          root_file: main.tex
          compiler: pdflatex
